version: "3"
services:
  backend-app:
    container_name: backend-app
    build:
      context: ../
      dockerfile: Dockerfile
    working_dir: "/app"
    volumes:
      - ../:/app
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8002:8080
